// Dados Iniciais e Atividades de Demonstração - Inglês Fácil
// 12 atividades distribuídas em Aeroporto, Hotel e Restaurante

import { Activity, User, UserSettings, ReviewItem } from '../../types';

export const DEMO_USERS: User[] = [
  {
    id: 'user-carlos-student',
    name: 'Carlos Silva',
    email: 'carlos.aluno@exemplo.com.br',
    role: 'student',
    status: 'active',
    createdAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'user-helena-admin',
    name: 'Prof.ª Helena Costa',
    email: 'helena.admin@inglesfacil.com.br',
    role: 'admin',
    status: 'active',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'user-mariana-student',
    name: 'Mariana Duarte',
    email: 'mariana.estudos@exemplo.com.br',
    role: 'student',
    status: 'active',
    createdAt: '2026-09-20T14:30:00Z',
  },
];

export const DEMO_SETTINGS: Record<string, UserSettings> = {
  'user-carlos-student': {
    userId: 'user-carlos-student',
    dailyGoalMinutes: 10,
    audioSpeed: 1.0,
    autoPlayAudio: true,
    reminders: {
      enabled: true,
      time: '19:30',
      daysOfWeek: [1, 2, 3, 4, 5], // Seg a Sex
      timezone: 'America/Sao_Paulo',
    },
  },
  'user-helena-admin': {
    userId: 'user-helena-admin',
    dailyGoalMinutes: 10,
    audioSpeed: 1.0,
    autoPlayAudio: true,
    reminders: {
      enabled: false,
      time: '08:00',
      daysOfWeek: [1, 3, 5],
      timezone: 'America/Sao_Paulo',
    },
  },
};

export const INITIAL_ACTIVITIES: Activity[] = [
  // --- AEROPORTO ---
  {
    id: 'act-air-01',
    version: 1,
    title: 'Chegando ao Aeroporto: Escuta e Frases Chave',
    description: 'Aprenda a reconhecer instruções básicas sonoras na chegada ao aeroporto internacional.',
    category: 'airport',
    modality: 'audio',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    isPublished: true,
    createdAt: '2026-09-10T10:00:00Z',
    questions: [
      {
        id: 'q-air-01-1',
        activityId: 'act-air-01',
        type: 'listening_choice',
        promptPt: 'Ouça o áudio e selecione o significado correto da frase anunciada:',
        audioPhraseEn: 'Please have your passport and boarding pass ready.',
        expectedAnswer: 'Por favor, tenha seu passaporte e cartão de embarque em mãos.',
        acceptedVariations: ['Por favor tenha seu passaporte e cartao de embarque em maos'],
        options: [
          { id: 'opt-1', text: 'Por favor, tenha seu passaporte e cartão de embarque em mãos.' },
          { id: 'opt-2', text: 'Por favor, dirija-se à esteira de bagagens número cinco.' },
          { id: 'opt-3', text: 'Seu voo está atrasado em trinta minutos.' },
          { id: 'opt-4', text: 'Apresente sua carteira de motorista na entrada.' },
        ],
        correctOptionId: 'opt-1',
        explanationPt: '"Boarding pass" é o cartão de embarque. "Ready" significa pronto ou em mãos para apresentar.',
        difficulty: 'beginner',
      },
      {
        id: 'q-air-01-2',
        activityId: 'act-air-01',
        type: 'dictation',
        promptPt: 'Ouça atentamente a frase e digite o que você escutou em inglês:',
        audioPhraseEn: 'Where is terminal two?',
        expectedAnswer: 'Where is terminal two?',
        acceptedVariations: ['Where is terminal 2?', 'Where is terminal two', 'Where is terminal 2'],
        explanationPt: 'A pergunta "Where is...?" significa "Onde fica...?" ou "Onde é...?". Muito usada em viagens.',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-air-02',
    version: 1,
    title: 'Mostrando seu Passaporte e Cartão de Embarque',
    description: 'Pratique a escrita e organização de frases para interagir no controle de segurança e imigração.',
    category: 'airport',
    modality: 'writing',
    difficulty: 'beginner',
    estimatedMinutes: 6,
    isPublished: true,
    createdAt: '2026-09-10T11:00:00Z',
    questions: [
      {
        id: 'q-air-02-1',
        activityId: 'act-air-02',
        type: 'fill_in_the_blanks',
        promptPt: 'Complete a frase com a palavra correta para dizer "Aqui está meu passaporte":\n"Here is my _______."',
        expectedAnswer: 'passport',
        acceptedVariations: ['passport.'],
        explanationPt: '"Here is my passport" é a forma mais educada e direta de entregar o documento ao oficial.',
        difficulty: 'beginner',
      },
      {
        id: 'q-air-02-2',
        activityId: 'act-air-02',
        type: 'word_reorder',
        promptPt: 'Organize as palavras abaixo para formar a frase em inglês:',
        scrambledWords: ['is', 'your', 'Here', 'boarding', 'pass'],
        expectedAnswer: 'Here is your boarding pass',
        acceptedVariations: ['Here is your boarding pass.'],
        explanationPt: 'Estrutura: "Here is" (Aqui está) + "your" (seu/sua) + objeto.',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-air-03',
    version: 1,
    title: 'Encontrando o Portão de Embarque (Gate)',
    description: 'Compreensão de áudio sobre informações de voo e numeração de portões.',
    category: 'airport',
    modality: 'audio',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    isPublished: true,
    createdAt: '2026-09-11T09:00:00Z',
    questions: [
      {
        id: 'q-air-03-1',
        activityId: 'act-air-03',
        type: 'listening_choice',
        promptPt: 'Ouça o anúncio e indique qual é o portão de embarque correto:',
        audioPhraseEn: 'Flight 304 is boarding at gate 15.',
        expectedAnswer: 'O voo 304 está embarcando no portão 15.',
        acceptedVariations: [],
        options: [
          { id: 'opt-1', text: 'O voo 304 está embarcando no portão 15.' },
          { id: 'opt-2', text: 'O voo 304 foi cancelado no portão 50.' },
          { id: 'opt-3', text: 'O voo 403 está pousando na pista 15.' },
          { id: 'opt-4', text: 'O voo 304 mudou para o portão 5.' },
        ],
        correctOptionId: 'opt-1',
        explanationPt: 'Atenção aos números em inglês: "fifteen" (15) tem o som no final diferente de "fifty" (50).',
        difficulty: 'beginner',
      },
      {
        id: 'q-air-03-2',
        activityId: 'act-air-03',
        type: 'dictation',
        promptPt: 'Ouça o áudio e digite o que você ouviu:',
        audioPhraseEn: 'Is this the flight to London?',
        expectedAnswer: 'Is this the flight to London?',
        acceptedVariations: ['Is this the flight to London', 'is this the flight to london'],
        explanationPt: 'Em perguntas com o verbo To Be, o verbo vem antes: "Is this...?" (Isto/Este é...?).',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-air-04',
    version: 1,
    title: 'Alfândega e Bagagem: Diálogo Prático',
    description: 'Responda a perguntas comuns sobre o motivo da viagem e quantidade de malas.',
    category: 'airport',
    modality: 'mixed',
    difficulty: 'beginner',
    estimatedMinutes: 7,
    isPublished: true,
    createdAt: '2026-09-12T14:00:00Z',
    questions: [
      {
        id: 'q-air-04-1',
        activityId: 'act-air-04',
        type: 'oral_practice',
        promptPt: 'Ouça a frase em inglês e grave sua repetição em voz alta para treinar sua pronúncia:',
        audioPhraseEn: 'I am here on vacation.',
        expectedAnswer: 'I am here on vacation.',
        acceptedVariations: ["I'm here on vacation.", 'I am here on vacation'],
        explanationPt: '"On vacation" significa "de férias". Nos Estados Unidos usa-se vacation; no Reino Unido é comum ouvir holiday.',
        difficulty: 'beginner',
      },
      {
        id: 'q-air-04-2',
        activityId: 'act-air-04',
        type: 'situational_response',
        promptPt: 'O oficial da alfândega pergunta: "How many bags do you have?" (Quantas malas você tem?). Responda que você tem uma mala:',
        expectedAnswer: 'I have one bag, please.',
        acceptedVariations: [
          'I have one bag',
          'I have one suitcase',
          'One bag',
          'Just one bag',
          'Only one bag',
        ],
        explanationPt: '"Bag" ou "suitcase" significam mala. Para uma mala: "one bag" ou "just one bag".',
        difficulty: 'beginner',
      },
    ],
  },

  // --- HOTEL ---
  {
    id: 'act-hot-05',
    version: 1,
    title: 'Check-in no Hotel: Escuta Atenta',
    description: 'Entenda as instruções da recepção ao chegar ao seu hotel.',
    category: 'hotel',
    modality: 'audio',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    isPublished: true,
    createdAt: '2026-09-13T10:00:00Z',
    questions: [
      {
        id: 'q-hot-05-1',
        activityId: 'act-hot-05',
        type: 'listening_choice',
        promptPt: 'Ouça a recepcionista e escolha o significado do que ela disse:',
        audioPhraseEn: 'Welcome! Do you have a reservation?',
        expectedAnswer: 'Bem-vindo! Você tem uma reserva?',
        acceptedVariations: [],
        options: [
          { id: 'opt-1', text: 'Bem-vindo! Você tem uma reserva?' },
          { id: 'opt-2', text: 'Boa tarde! O café da manhã é gratuito?' },
          { id: 'opt-3', text: 'Olá! Seu quarto ainda não está limpo.' },
          { id: 'opt-4', text: 'Por favor, assine este documento de saída.' },
        ],
        correctOptionId: 'opt-1',
        explanationPt: '"Reservation" é reserva. "Do you have...?" é a pergunta clássica: "Você tem...?".',
        difficulty: 'beginner',
      },
      {
        id: 'q-hot-05-2',
        activityId: 'act-hot-05',
        type: 'dictation',
        promptPt: 'Digite em inglês a frase dita pelo recepcionista:',
        audioPhraseEn: 'Your room is on the third floor.',
        expectedAnswer: 'Your room is on the third floor.',
        acceptedVariations: ['Your room is on the 3rd floor.', 'Your room is on the third floor', 'Your room is on the 3rd floor'],
        explanationPt: '"Third floor" é o terceiro andar. Em inglês usa-se a preposição "on" para andares de edifícios.',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-hot-06',
    version: 1,
    title: 'Pedindo a Senha do Wi-Fi e Toalhas Extras',
    description: 'Escreva solicitações comuns que você precisará fazer durante sua estadia.',
    category: 'hotel',
    modality: 'writing',
    difficulty: 'beginner',
    estimatedMinutes: 6,
    isPublished: true,
    createdAt: '2026-09-14T11:00:00Z',
    questions: [
      {
        id: 'q-hot-06-1',
        activityId: 'act-hot-06',
        type: 'translation',
        promptPt: 'Traduza para o inglês de forma educada: "Qual é a senha do Wi-Fi?"',
        expectedAnswer: 'What is the Wi-Fi password?',
        acceptedVariations: [
          "What's the Wi-Fi password?",
          "What is the wifi password?",
          "What's the wifi password?",
          "What is the Wi-Fi password, please?",
          "What is the Wi-Fi password"
        ],
        explanationPt: '"Password" é a senha. "Wi-Fi" pronuncia-se "uai-fai" em inglês.',
        difficulty: 'beginner',
      },
      {
        id: 'q-hot-06-2',
        activityId: 'act-hot-06',
        type: 'fill_in_the_blanks',
        promptPt: 'Complete a frase para pedir toalhas adicionais:\n"Could I have extra _______, please?" (toalhas)',
        expectedAnswer: 'towels',
        acceptedVariations: ['towels.'],
        explanationPt: '"Towel" é toalha. O plural é "towels". "Could I have...?" é um jeito muito simpático e educado de pedir algo.',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-hot-07',
    version: 1,
    title: 'Informações sobre o Café da Manhã (Breakfast)',
    description: 'Prática de escuta e fala sobre horários do café no hotel.',
    category: 'hotel',
    modality: 'audio',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    isPublished: true,
    createdAt: '2026-09-15T15:00:00Z',
    questions: [
      {
        id: 'q-hot-07-1',
        activityId: 'act-hot-07',
        type: 'listening_choice',
        promptPt: 'Ouça o aviso e marque qual é o horário do café da manhã:',
        audioPhraseEn: 'Breakfast is served from seven to ten a.m.',
        expectedAnswer: 'O café da manhã é servido das sete às dez da manhã.',
        acceptedVariations: [],
        options: [
          { id: 'opt-1', text: 'O café da manhã é servido das sete às dez da manhã.' },
          { id: 'opt-2', text: 'O almoço começa às onze horas da manhã.' },
          { id: 'opt-3', text: 'O café da manhã encerra às sete horas.' },
          { id: 'opt-4', text: 'O restaurante fecha às dez da noite.' },
        ],
        correctOptionId: 'opt-1',
        explanationPt: '"From... to..." indica o intervalo "de... até...". "a.m." refere-se ao período da manhã (antes do meio-dia).',
        difficulty: 'beginner',
      },
      {
        id: 'q-hot-07-2',
        activityId: 'act-hot-07',
        type: 'oral_practice',
        promptPt: 'Ouça a frase em inglês e grave a repetição para praticar sua pronúncia:',
        audioPhraseEn: 'Is breakfast included in the room price?',
        expectedAnswer: 'Is breakfast included in the room price?',
        acceptedVariations: ['Is breakfast included in the room price'],
        explanationPt: '"Included" significa incluído. Uma dúvida clássica de todo viajante!',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-hot-08',
    version: 1,
    title: 'Horário de Check-out e Pagamento',
    description: 'Organização de frases e respostas no momento de encerrar sua hospedagem.',
    category: 'hotel',
    modality: 'mixed',
    difficulty: 'beginner',
    estimatedMinutes: 6,
    isPublished: true,
    createdAt: '2026-09-16T16:00:00Z',
    questions: [
      {
        id: 'q-hot-08-1',
        activityId: 'act-hot-08',
        type: 'word_reorder',
        promptPt: 'Organize as palavras para perguntar: "Que horas é o check-out?"',
        scrambledWords: ['is', 'time', 'check-out', 'What'],
        expectedAnswer: 'What time is check-out',
        acceptedVariations: ['What time is check-out?', 'What time is checkout?'],
        explanationPt: '"What time is...?" significa "Que horas é...?". Simples e essencial para não pagar diária extra.',
        difficulty: 'beginner',
      },
      {
        id: 'q-hot-08-2',
        activityId: 'act-hot-08',
        type: 'situational_response',
        promptPt: 'A recepção pergunta como você prefere pagar a conta. Responda que quer pagar com cartão de crédito:',
        expectedAnswer: 'By credit card, please.',
        acceptedVariations: [
          'By credit card',
          'With credit card',
          'Credit card, please',
          'Credit card',
          'I want to pay by credit card',
          'I would like to pay with credit card'
        ],
        explanationPt: 'Dizer "By credit card, please" ou "Credit card" é natural e suficiente no dia a dia.',
        difficulty: 'beginner',
      },
    ],
  },

  // --- RESTAURANTE ---
  {
    id: 'act-res-09',
    version: 1,
    title: 'Pedindo uma Mesa para Dois',
    description: 'Treine a audição para entender o recepcionista (host) do restaurante.',
    category: 'restaurant',
    modality: 'audio',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    isPublished: true,
    createdAt: '2026-09-17T12:00:00Z',
    questions: [
      {
        id: 'q-res-09-1',
        activityId: 'act-res-09',
        type: 'listening_choice',
        promptPt: 'Ouça o recepcionista do restaurante e marque a tradução correta:',
        audioPhraseEn: 'Table for two? Right this way, please.',
        expectedAnswer: 'Mesa para dois? Por aqui, por favor.',
        acceptedVariations: [],
        options: [
          { id: 'opt-1', text: 'Mesa para dois? Por aqui, por favor.' },
          { id: 'opt-2', text: 'Temos apenas mesas para quatro pessoas.' },
          { id: 'opt-3', text: 'O restaurante está lotado no momento.' },
          { id: 'opt-4', text: 'Deseja ver o cardápio de bebidas?' },
        ],
        correctOptionId: 'opt-1',
        explanationPt: '"Right this way" é a expressão usada para conduzir você ("por aqui" ou "siga-me").',
        difficulty: 'beginner',
      },
      {
        id: 'q-res-09-2',
        activityId: 'act-res-09',
        type: 'dictation',
        promptPt: 'Ouça a frase em inglês e digite o que escutou:',
        audioPhraseEn: 'Can we have a menu, please?',
        expectedAnswer: 'Can we have a menu, please?',
        acceptedVariations: ['Can we have a menu please?', 'Can we have the menu, please?', 'Can we have a menu'],
        explanationPt: '"Menu" pronuncia-se "mén-iu". "Can we have...?" é como dizemos "Pode nos trazer...?".',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-res-10',
    version: 1,
    title: 'Pedindo um Café e Água sem Gás',
    description: 'Aprenda a fazer pedidos básicos e pedir água da maneira que você deseja.',
    category: 'restaurant',
    modality: 'writing',
    difficulty: 'beginner',
    estimatedMinutes: 5,
    isPublished: true,
    createdAt: '2026-09-18T15:00:00Z',
    questions: [
      {
        id: 'q-res-10-1',
        activityId: 'act-res-10',
        type: 'situational_response',
        promptPt: 'O garçom chega e diz "What can I get for you?". Peça um café com leite, por favor:',
        expectedAnswer: 'A coffee with milk, please.',
        acceptedVariations: [
          'Coffee with milk, please',
          'Coffee with milk',
          'I would like a coffee with milk, please',
          "I'd like a coffee with milk, please",
          "I'd like a coffee with milk",
          'One coffee with milk, please'
        ],
        explanationPt: '"Coffee with milk" é café com leite. "I would like" ou simplesmente o item seguido de "please" é muito educado.',
        difficulty: 'beginner',
      },
      {
        id: 'q-res-10-2',
        activityId: 'act-res-10',
        type: 'fill_in_the_blanks',
        promptPt: 'Complete com a palavra que significa água sem gás:\n"Still _______, please."',
        expectedAnswer: 'water',
        acceptedVariations: ['water.'],
        explanationPt: '"Still water" é água sem gás; "Sparkling water" é água com gás.',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-res-11',
    version: 1,
    title: 'Escolhendo a Refeição e Restrições',
    description: 'Tradução e ordenação de frases para informar preferências culinárias.',
    category: 'restaurant',
    modality: 'writing',
    difficulty: 'beginner',
    estimatedMinutes: 6,
    isPublished: true,
    createdAt: '2026-09-19T13:00:00Z',
    questions: [
      {
        id: 'q-res-11-1',
        activityId: 'act-res-11',
        type: 'translation',
        promptPt: 'Traduza para o inglês: "Eu gostaria de ver as opções vegetarianas."',
        expectedAnswer: 'I would like to see the vegetarian options.',
        acceptedVariations: [
          "I'd like to see the vegetarian options.",
          "I would like to see the vegetarian options",
          "I'd like to see the vegetarian options"
        ],
        explanationPt: '"I would like to see" = "Eu gostaria de ver". "Vegetarian options" = opções vegetarianas.',
        difficulty: 'beginner',
      },
      {
        id: 'q-res-11-2',
        activityId: 'act-res-11',
        type: 'word_reorder',
        promptPt: 'Ordene as palavras para dizer: "A comida está deliciosa, obrigado."',
        scrambledWords: ['delicious,', 'The', 'is', 'food', 'thank', 'you.'],
        expectedAnswer: 'The food is delicious, thank you.',
        acceptedVariations: ['The food is delicious thank you', 'The food is delicious, thank you'],
        explanationPt: 'Elogiar o prato é sempre bem recebido pelos atendentes!',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'act-res-12',
    version: 1,
    title: 'Pedindo a Conta (The Check, Please)',
    description: 'Finalize a refeição pedindo a conta com clareza em inglês.',
    category: 'restaurant',
    modality: 'mixed',
    difficulty: 'beginner',
    estimatedMinutes: 6,
    isPublished: true,
    createdAt: '2026-09-20T17:00:00Z',
    questions: [
      {
        id: 'q-res-12-1',
        activityId: 'act-res-12',
        type: 'oral_practice',
        promptPt: 'Ouça e pratique a frase falada ao chamar o garçom para pagar a conta:',
        audioPhraseEn: 'Excuse me, could we have the check, please?',
        expectedAnswer: 'Excuse me, could we have the check, please?',
        acceptedVariations: [
          'Excuse me, could we have the check, please',
          'Excuse me, could we have the bill, please?'
        ],
        explanationPt: 'Nos EUA diz-se "the check"; no Reino Unido e Europa é comum ouvir "the bill". Ambas são amplamente compreendidas.',
        difficulty: 'beginner',
      },
      {
        id: 'q-res-12-2',
        activityId: 'act-res-12',
        type: 'dictation',
        promptPt: 'Ouça o áudio e digite em inglês a confirmação do garçom:',
        audioPhraseEn: 'Sure, here is your receipt.',
        expectedAnswer: 'Sure, here is your receipt.',
        acceptedVariations: ['Sure, here is your receipt', 'Sure here is your receipt'],
        explanationPt: 'Atenção à pronúncia de "receipt" (recibo/comprovante): a letra "p" é muda, pronuncia-se "re-siit".',
        difficulty: 'beginner',
      },
    ],
  },
];

export const INITIAL_REVIEW_ITEMS: ReviewItem[] = [
  {
    id: 'rev-01',
    userId: 'user-carlos-student',
    questionId: 'q-air-01-2',
    activityId: 'act-air-01',
    phraseEn: 'Where is terminal two?',
    translationPt: 'Onde fica o terminal dois?',
    category: 'airport',
    consecutiveCorrect: 0,
    intervalDays: 1,
    nextReviewDate: new Date().toISOString(), // Pronto para revisar hoje
    lastAttemptDate: '2026-09-30T19:00:00Z',
    totalMistakes: 1,
  },
  {
    id: 'rev-02',
    userId: 'user-carlos-student',
    questionId: 'q-hot-06-1',
    activityId: 'act-hot-06',
    phraseEn: 'What is the Wi-Fi password?',
    translationPt: 'Qual é a senha do Wi-Fi?',
    category: 'hotel',
    consecutiveCorrect: 1,
    intervalDays: 3,
    nextReviewDate: new Date().toISOString(), // Pronto para revisar hoje
    lastAttemptDate: '2026-09-28T20:00:00Z',
    totalMistakes: 2,
  },
  {
    id: 'rev-03',
    userId: 'user-carlos-student',
    questionId: 'q-res-10-2',
    activityId: 'act-res-10',
    phraseEn: 'Still water, please.',
    translationPt: 'Água sem gás, por favor.',
    category: 'restaurant',
    consecutiveCorrect: 2,
    intervalDays: 7,
    nextReviewDate: new Date(Date.now() + 86400000 * 4).toISOString(), // Em 4 dias
    lastAttemptDate: '2026-09-25T18:00:00Z',
    totalMistakes: 1,
  },
];
